### PR TITLE
Add contact link to footer

### LINKED ISSUE #245: Add "Contact us" link in footer of canonical.com
Please add a "Contact us" link in footer of canonical.com. Please follow the styling and position of the same button on ubuntu.com (see screen shot). 
image

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add contact link to footer

## QA

1. Check out this feature branch
2. Run the site using the command `./run`
3. View the site locally in your web browser at: [http://0.0.0.0:8002/](http://0.0.0.0:8002/)
4. Look at the footer on any page and make sure the contact us link/button is there

## Issue / Card

[Fixes #245](https://app.zenhub.com/workspace/o/canonical-websites/www.canonical.com/issues/245)

## Screenshots

canonical the company behind ubuntu

### CODE REVIEW

**Comment by steverydz** [comment]
@anthonydillon I pulled this button from www.ubuntu.com which already had that class. Happy to remove it, but was trying to follow existing patterns.

**Comment by frankiegranato** [comment]
Hi @steverydz 
- Lets keep the contact us button visible on small screens (I think on u.com the button turns into a text link?)
- I'm thinking we should point the link at: https://www.ubuntu.com/contact-us (it is a more useful page, although maybe its confusing to point to an external page - any thoughts welcome? @anthonydillon & @steverydz)
- Finally, I know this isn't connected to this work, but I wish the last three characters of the copyright sentence could live on the same line. Is this easy to do? 
canonical window snag

**Comment by steverydz** [comment]
@frankiegranato I've removed the hide class, updated the link and fixed the line wrapping on the copyright statement.

**Comment by frankiegranato** [comment]
Thank you for updating the link destination. 
I still see the line wrapping on the copyright statement though :-(

**Comment by steverydz** [comment]
@frankiegranato Can you try a hard refresh? Might have cached the CSS?

**Comment by frankiegranato** [comment]
Thank you @steverydz (I cleared my cache and it worked)

**Pull request merged**
