### PR TITLE
remove the Chinese trademark background

### PR DESCRIPTION
**Pull request by binli**
Removed the background png.

### CODE REVIEW

**Comment by anthonydillon** [comment]
Thank you for this PR. After consulting the designers here at Canonical we would like to keep the image row by cropping the banners out or replacing the image completely.

**Comment by anthonydillon** [comment]
@yaili what would you suggest?

**Comment by yaili** [comment]
@anthonydillon agree with your suggestion. Wouldn't crop the top still leave the problem of the t-shirts having the logo?

**Comment by anthonydillon** [comment]
Oh your right. I didn't see them there. Could we replace the image with
maybe one from MWC?

**Comment by yaili** [comment]
@anthonydillon Sure. I'm not sure who has those though… @magdalena-mirowicz @pmahnke do you know?

**Comment by pmahnke** [comment]
@anthonydillon I do not... ask Marcus?

**Comment by anthonydillon** [comment]
@binli Thank you very much for this branch. This has been superseded by https://github.com/canonical-websites/www.canonical.com/pull/125.

**Pull request closed without merging**
