### PR TITLE
Design feedback on /about

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

See design review: https://github.com/ubuntudesign/vanilla-squad/issues/58

## QA

- Pull code
- Run `./run serve --watch`
- Check http://0.0.0.0:8002/about against checklist above

## Issue / Card

Fixes https://github.com/ubuntudesign/vanilla-squad/issues/58

### CODE REVIEW

**Comment by kwm14** [comment]
## Design feedback

### Hero
- [ ] Update 'At Canonical, we believe in' section grid layout to `.col-7` `.col-5`

### Our management team
- [ ] Update pull-quote font-size: `1.5rem;`
- [ ] Update content-card background-color: `$color-x-light`
- [ ] Update Anand Krishnan image to: https://assets.ubuntu.com/v1/74c207a8-Anand+Krishnan-canonical.png
- [ ] Remove margin-top from 'jobTitle'
- [ ] 'Name' and 'jobTitle' align top of profile image
- [ ] Update tabbed-menu font-color: `$color-dark`

### Google Maps
- [ ] Pins not clickable so unable to see location dialog boxes

### Enquiries
- [ ] Remove margin-top from **p** tag
- [ ] Remove icon from `$breakpoint-medium` and `$breakpoint-small`

### Further information
- [ ] Update link-color to: `#E95420`
- [ ] Update p-list--divided margin-top to: `16px;`

### Contact us
- [ ] Update **p** tag margin-top to: `16px;`

**Comment by barrymcgee** [comment]
@kwm14 

- Map pins - this is a weirdness with Google Maps that has stumped me. May need someone else to help.
- Last point - this request will mean we're overriding Vanilla core vertical rhythm, is this something we should be changing in Vanilla?

**Comment by kwm14** [comment]
@barrymcgee 

- Map pins - Ok no problem. It's not really a design-related issue more dev so I will re-review your changes now
- Contact us - Ok we will leave it as is. The vertical rhythm has just been finalised so I don't want to start proposing changes
- Will I need a new demo link or will the existing one pull down your changes?

**Comment by barrymcgee** [comment]
@kwm14 You'll need another demo built but right now they are broken. Have got @WillMoggridge on the case so hopefully, they should be back up soon.

**Comment by barrymcgee** [comment]
New demo: http://www.canonical.com-pr-175.run.demo.haus/about

**Comment by kwm14** [comment]
## Design feedback

### Our management team
- [ ] Seb Butter name is incorrect in his profile
- [ ] Seb Butter missing margin in-between body copy and external link
- [ ] Jane Silber name and role should be aligned to top

**Comment by barrymcgee** [comment]
New demo: http://www.canonical.com-pr-176.run.demo.haus/about

**Pull request merged**
