### PR TITLE
Update the animation elements to line up correctly

### LINKED ISSUE #183: Products animation misaligned
## Summary

The components of the animation on the products page aren't correctly aligned

## Process

Go to /products and see the animation in the hero

## Current and expected result

Current:
products-new

Expected (current live):

products-live

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Lined the images in the animation on the /products

## QA

Go to the [products page](http://localhost:8002/products)
See that the images in the hero animation are properly arranged.

## Issue / Card

Fixes #183

### CODE REVIEW

**Comment by deadlight** [comment]
I'm going to re-do this. Turns out the bug was caused by the new vertical margins and that can be fixed better.

**Comment by anthonydillon** [comment]
@deadlight Updated this branch, mind reviewing the changes?

**Comment by deadlight** [comment]
@anthonydillon I didn't see that you had done anything and rewrote the history of this branch with my own fix. Can you confirm that my fix works, please?

**Comment by anthonydillon** [comment]
I updated the code to remove margin top. Instead of changing the top values.

It works but as I made the change it will need you to test it and review.

**Pull request merged**
