### PR TITLE
Feeds example

### PR DESCRIPTION
**Pull request by nottrobin**
**Do not merge**

### CODE REVIEW

**Comment by anthonydillon** [comment]
@nottrobin @pmahnke is this PR still valid/required?

**Comment by nottrobin** [comment]
@anthonydillon I believe @pmahnke is actively working on it, possibly with @WillMoggridge's help.

**Comment by pmahnke** [comment]
@nottrobin I think it was replaced with https://github.com/canonical-websites/www.canonical.com/pull/221 now... raw-feeds.py is in there.

**Comment by nottrobin** [comment]
@pmahnke cool. Closing.

**Comment by anthonydillon** [comment]
Ta muchly

**Pull request closed without merging**
